// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kRo3oVnl5fV9-rv9m9zHVjNHYnbUkBs',
    appId: '1:385306573264:web:785b65ab72cb549242a1d5',
    messagingSenderId: '385306573264',
    projectId: 'dolceresetapp-982cd',
    authDomain: 'dolceresetapp-982cd.firebaseapp.com',
    storageBucket: 'dolceresetapp-982cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0GGohjP0Ga_64Tm-jq5TIm-gfKg8Rc0',
    appId: '1:385306573264:android:fca8db16a37e2a0442a1d5',
    messagingSenderId: '385306573264',
    projectId: 'dolceresetapp-982cd',
    storageBucket: 'dolceresetapp-982cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8lbhJaEqnOdUf-d0AH6uhOa2ik8qNn5k',
    appId: '1:385306573264:ios:8c957b05aa5099d442a1d5',
    messagingSenderId: '385306573264',
    projectId: 'dolceresetapp-982cd',
    storageBucket: 'dolceresetapp-982cd.firebasestorage.app',
    iosBundleId: 'com.dolceresetltd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8lbhJaEqnOdUf-d0AH6uhOa2ik8qNn5k',
    appId: '1:385306573264:ios:8c957b05aa5099d442a1d5',
    messagingSenderId: '385306573264',
    projectId: 'dolceresetapp-982cd',
    storageBucket: 'dolceresetapp-982cd.firebasestorage.app',
    iosBundleId: 'com.dolceresetltd.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5kRo3oVnl5fV9-rv9m9zHVjNHYnbUkBs',
    appId: '1:385306573264:web:aca902025a7dabe842a1d5',
    messagingSenderId: '385306573264',
    projectId: 'dolceresetapp-982cd',
    authDomain: 'dolceresetapp-982cd.firebaseapp.com',
    storageBucket: 'dolceresetapp-982cd.firebasestorage.app',
  );
}
